[package]
name = "cryptopals"
version = "0.1.0"
edition = "2021"

[dependencies]
openssl = "0.10.71"
rand = "0.8.5"
hex-literal = "0.4.1"
num-bigint = { version = "0.4.6", features = ["rand"] }
num-traits = "0.2.19"
num-integer = "0.1.46"
